"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentMailClient = void 0;
const Client_1 = require("./api/resources/inboxes/client/Client");
const Client_2 = require("./api/resources/contexts/client/Client");
const Client_3 = require("./api/resources/drafts/client/Client");
const Client_4 = require("./api/resources/threads/client/Client");
const Client_5 = require("./api/resources/webhooks/client/Client");
class AgentMailClient {
    constructor(_options = {}) {
        this._options = _options;
    }
    get inboxes() {
        var _a;
        return ((_a = this._inboxes) !== null && _a !== void 0 ? _a : (this._inboxes = new Client_1.Inboxes(this._options)));
    }
    get contexts() {
        var _a;
        return ((_a = this._contexts) !== null && _a !== void 0 ? _a : (this._contexts = new Client_2.Contexts(this._options)));
    }
    get drafts() {
        var _a;
        return ((_a = this._drafts) !== null && _a !== void 0 ? _a : (this._drafts = new Client_3.Drafts(this._options)));
    }
    get threads() {
        var _a;
        return ((_a = this._threads) !== null && _a !== void 0 ? _a : (this._threads = new Client_4.Threads(this._options)));
    }
    get webhooks() {
        var _a;
        return ((_a = this._webhooks) !== null && _a !== void 0 ? _a : (this._webhooks = new Client_5.Webhooks(this._options)));
    }
}
exports.AgentMailClient = AgentMailClient;
