/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as AgentMail from "../../../../../index";
export declare namespace Drafts {
    interface Options {
        environment?: core.Supplier<environments.AgentMailEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<core.BearerToken | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Drafts {
    protected readonly _options: Drafts.Options;
    constructor(_options?: Drafts.Options);
    /**
     * @param {AgentMail.inboxes.InboxId} inboxId
     * @param {AgentMail.inboxes.ListDraftsRequest} request
     * @param {Drafts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentMail.NotFoundError}
     *
     * @example
     *     await client.inboxes.drafts.list("inbox_id")
     */
    list(inboxId: AgentMail.inboxes.InboxId, request?: AgentMail.inboxes.ListDraftsRequest, requestOptions?: Drafts.RequestOptions): Promise<AgentMail.ListDraftsResponse>;
    /**
     * @param {AgentMail.inboxes.InboxId} inboxId
     * @param {AgentMail.DraftId} draftId
     * @param {Drafts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentMail.NotFoundError}
     *
     * @example
     *     await client.inboxes.drafts.get("inbox_id", "draft_id")
     */
    get(inboxId: AgentMail.inboxes.InboxId, draftId: AgentMail.DraftId, requestOptions?: Drafts.RequestOptions): Promise<AgentMail.Draft>;
    /**
     * @param {AgentMail.inboxes.InboxId} inboxId
     * @param {AgentMail.CreateDraftRequest} request
     * @param {Drafts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentMail.NotFoundError}
     *
     * @example
     *     await client.inboxes.drafts.create("inbox_id", {
     *         labels: undefined,
     *         replyTo: undefined,
     *         to: undefined,
     *         cc: undefined,
     *         bcc: undefined,
     *         subject: undefined,
     *         text: undefined,
     *         html: undefined
     *     })
     */
    create(inboxId: AgentMail.inboxes.InboxId, request: AgentMail.CreateDraftRequest, requestOptions?: Drafts.RequestOptions): Promise<AgentMail.Draft>;
    /**
     * @param {AgentMail.inboxes.InboxId} inboxId
     * @param {AgentMail.DraftId} draftId
     * @param {AgentMail.UpdateMessageRequest} request
     * @param {Drafts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentMail.NotFoundError}
     * @throws {@link AgentMail.ValidationError}
     * @throws {@link AgentMail.MessageRejectedError}
     *
     * @example
     *     await client.inboxes.drafts.send("inbox_id", "draft_id", {
     *         addLabels: undefined,
     *         removeLabels: undefined
     *     })
     */
    send(inboxId: AgentMail.inboxes.InboxId, draftId: AgentMail.DraftId, request: AgentMail.UpdateMessageRequest, requestOptions?: Drafts.RequestOptions): Promise<AgentMail.SendMessageResponse>;
    protected _getAuthorizationHeader(): Promise<string>;
}
