/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageLabels: core.serialization.Schema<serializers.MessageLabels.Raw, AgentMail.MessageLabels>;
export declare namespace MessageLabels {
    type Raw = string[];
}
