/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { MessageLabels } from "./MessageLabels";
import { SendMessageReplyTo } from "./SendMessageReplyTo";
import { SendMessageTo } from "./SendMessageTo";
import { SendMessageCc } from "./SendMessageCc";
import { SendMessageBcc } from "./SendMessageBcc";
import { MessageSubject } from "./MessageSubject";
import { MessageText } from "./MessageText";
import { MessageHtml } from "./MessageHtml";
import { SendMessageAttachments } from "./SendMessageAttachments";
export declare const SendMessageRequest: core.serialization.ObjectSchema<serializers.SendMessageRequest.Raw, AgentMail.SendMessageRequest>;
export declare namespace SendMessageRequest {
    interface Raw {
        labels?: MessageLabels.Raw | null;
        reply_to?: SendMessageReplyTo.Raw | null;
        to?: SendMessageTo.Raw | null;
        cc?: SendMessageCc.Raw | null;
        bcc?: SendMessageBcc.Raw | null;
        subject?: MessageSubject.Raw | null;
        text?: MessageText.Raw | null;
        html?: MessageHtml.Raw | null;
        attachments?: SendMessageAttachments.Raw | null;
    }
}
