/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { SendAttachment } from "../../attachments/types/SendAttachment";
export declare const SendMessageAttachments: core.serialization.Schema<serializers.SendMessageAttachments.Raw, AgentMail.SendMessageAttachments>;
export declare namespace SendMessageAttachments {
    type Raw = SendAttachment.Raw[];
}
