/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { MessageId } from "./MessageId";
import { ThreadId } from "../../threads/types/ThreadId";
export declare const SendMessageResponse: core.serialization.ObjectSchema<serializers.SendMessageResponse.Raw, AgentMail.SendMessageResponse>;
export declare namespace SendMessageResponse {
    interface Raw {
        message_id: MessageId.Raw;
        thread_id: ThreadId.Raw;
    }
}
