"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentMailApiTimeoutError = void 0;
class AgentMailApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, AgentMailApiTimeoutError.prototype);
    }
}
exports.AgentMailApiTimeoutError = AgentMailApiTimeoutError;
