/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { ClientId } from "./ClientId";
export declare const CreateInboxRequest: core.serialization.ObjectSchema<serializers.inboxes.CreateInboxRequest.Raw, AgentMail.inboxes.CreateInboxRequest>;
export declare namespace CreateInboxRequest {
    interface Raw {
        username?: string | null;
        domain?: string | null;
        display_name?: string | null;
        client_id?: ClientId.Raw | null;
    }
}
