// Auto-generated by @fern-api/cli-generator's copySpecs step.
// Edit the SDK template / generator if you need to change the shape.

use fern_cli_sdk::openapi::CliApp;

fn main() {
    CliApp::new("agentmail")
        .spec(include_str!("openapi0.json"))
        .auth_scheme_env("BearerAuth", "AGENTMAIL_TOKEN")
        .run()
}
