/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { Url } from "./Url";
import { EventTypes } from "./EventTypes";
import { InboxIds } from "./InboxIds";
import { ClientId } from "./ClientId";
export declare const CreateWebhookRequest: core.serialization.ObjectSchema<serializers.CreateWebhookRequest.Raw, AgentMail.CreateWebhookRequest>;
export declare namespace CreateWebhookRequest {
    interface Raw {
        url: Url.Raw;
        event_types: EventTypes.Raw;
        inbox_ids?: InboxIds.Raw | null;
        client_id?: ClientId.Raw | null;
    }
}
