/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { WebhookId } from "./WebhookId";
import { Url } from "./Url";
import { EventTypes } from "./EventTypes";
import { InboxIds } from "./InboxIds";
import { ClientId } from "./ClientId";
export declare const Webhook: core.serialization.ObjectSchema<serializers.Webhook.Raw, AgentMail.Webhook>;
export declare namespace Webhook {
    interface Raw {
        webhook_id: WebhookId.Raw;
        url: Url.Raw;
        event_types?: EventTypes.Raw | null;
        inbox_ids?: InboxIds.Raw | null;
        secret: string;
        enabled: boolean;
        updated_at: string;
        created_at: string;
        client_id?: ClientId.Raw | null;
    }
}
