/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const ThreadPreview: core.serialization.Schema<serializers.ThreadPreview.Raw, AgentMail.ThreadPreview>;
export declare namespace ThreadPreview {
    type Raw = string;
}
