/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const ThreadMessageCount: core.serialization.Schema<serializers.ThreadMessageCount.Raw, AgentMail.ThreadMessageCount>;
export declare namespace ThreadMessageCount {
    type Raw = number;
}
