/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as core from "../../../../core";
export declare const ThreadNotFoundError: core.serialization.Schema<serializers.ThreadNotFoundError.Raw, string>;
export declare namespace ThreadNotFoundError {
    type Raw = string;
}
