/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index";
import * as AgentMailApi from "../index";
export declare class ValidationError extends errors.AgentMailApiError {
    constructor(body: AgentMailApi.ValidationErrorResponse);
}
