/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const ThreadTimestamp: core.serialization.Schema<serializers.ThreadTimestamp.Raw, AgentMail.ThreadTimestamp>;
export declare namespace ThreadTimestamp {
    type Raw = string;
}
