/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { Attachment } from "../../attachments/types/Attachment";
export declare const ThreadAttachments: core.serialization.Schema<serializers.ThreadAttachments.Raw, AgentMail.ThreadAttachments>;
export declare namespace ThreadAttachments {
    type Raw = Attachment.Raw[];
}
