/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const ThreadLabels: core.serialization.Schema<serializers.ThreadLabels.Raw, AgentMail.ThreadLabels>;
export declare namespace ThreadLabels {
    type Raw = string[];
}
