/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const ThreadSenders: core.serialization.Schema<serializers.ThreadSenders.Raw, AgentMail.ThreadSenders>;
export declare namespace ThreadSenders {
    type Raw = string[];
}
