/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as AgentMail from "../../api/index";
import * as core from "../../core";
export declare const Ascending: core.serialization.Schema<serializers.Ascending.Raw, AgentMail.Ascending>;
export declare namespace Ascending {
    type Raw = boolean;
}
