/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as AgentMail from "../../api/index";
import * as core from "../../core";
export declare const Count: core.serialization.Schema<serializers.Count.Raw, AgentMail.Count>;
export declare namespace Count {
    type Raw = number;
}
