/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as AgentMail from "../../api/index";
import * as core from "../../core";
import { ErrorName } from "./ErrorName";
export declare const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, AgentMail.ErrorResponse>;
export declare namespace ErrorResponse {
    interface Raw {
        name: ErrorName.Raw;
        message: string;
    }
}
