/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as AgentMail from "../../api/index";
import * as core from "../../core";
export declare const Limit: core.serialization.Schema<serializers.Limit.Raw, AgentMail.Limit>;
export declare namespace Limit {
    type Raw = number;
}
