/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { DisplayName } from "./DisplayName";
export declare const CreateInboxRequest: core.serialization.ObjectSchema<serializers.CreateInboxRequest.Raw, AgentMailApi.CreateInboxRequest>;
export declare namespace CreateInboxRequest {
    interface Raw {
        username?: string | null;
        domain?: string | null;
        display_name?: DisplayName.Raw | null;
    }
}
