/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const DisplayName: core.serialization.Schema<serializers.DisplayName.Raw, AgentMailApi.DisplayName>;
export declare namespace DisplayName {
    type Raw = string;
}
