/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { Inbox } from "./Inbox";
import { Limit } from "../../../types/Limit";
import { Count } from "../../../types/Count";
import { LastKey } from "../../../types/LastKey";
export declare const ListInboxesResponse: core.serialization.ObjectSchema<serializers.ListInboxesResponse.Raw, AgentMailApi.ListInboxesResponse>;
export declare namespace ListInboxesResponse {
    interface Raw {
        inboxes: Inbox.Raw[];
        limit: Limit.Raw;
        count: Count.Raw;
        last_key?: LastKey.Raw;
    }
}
