/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as core from "../../../../core";
export declare const AddressTakenError: core.serialization.Schema<serializers.AddressTakenError.Raw, string>;
export declare namespace AddressTakenError {
    type Raw = string;
}
