/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as core from "../../../../core";
export declare const InboxNotFoundError: core.serialization.Schema<serializers.InboxNotFoundError.Raw, string>;
export declare namespace InboxNotFoundError {
    type Raw = string;
}
