/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const AgentMailApiEnvironment: {
    readonly Production: "https://api.agentmail.to";
};
export type AgentMailApiEnvironment = typeof AgentMailApiEnvironment.Production;
