/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const Addresses: core.serialization.Schema<serializers.Addresses.Raw, AgentMailApi.Addresses>;
export declare namespace Addresses {
    type Raw = string | string[];
}
