/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { AttachmentId } from "./AttachmentId";
export declare const Attachment: core.serialization.ObjectSchema<serializers.Attachment.Raw, AgentMailApi.Attachment>;
export declare namespace Attachment {
    interface Raw {
        attachment_id: AttachmentId.Raw;
        filename: string;
        mime_type: string;
        size: number;
        inline: boolean;
    }
}
