/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const AttachmentId: core.serialization.Schema<serializers.AttachmentId.Raw, AgentMailApi.AttachmentId>;
export declare namespace AttachmentId {
    type Raw = string;
}
