/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageItem } from "./MessageItem";
import { Limit } from "../../../types/Limit";
import { Count } from "../../../types/Count";
import { LastKey } from "../../../types/LastKey";
export declare const ListMessagesResponse: core.serialization.ObjectSchema<serializers.ListMessagesResponse.Raw, AgentMailApi.ListMessagesResponse>;
export declare namespace ListMessagesResponse {
    interface Raw {
        messages: MessageItem.Raw[];
        limit: Limit.Raw;
        count: Count.Raw;
        last_key?: LastKey.Raw;
    }
}
