/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageBcc: core.serialization.Schema<serializers.MessageBcc.Raw, AgentMailApi.MessageBcc>;
export declare namespace MessageBcc {
    type Raw = string[] | null | undefined;
}
