/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageCc: core.serialization.Schema<serializers.MessageCc.Raw, AgentMailApi.MessageCc>;
export declare namespace MessageCc {
    type Raw = string[] | null | undefined;
}
