"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Message = void 0;
const core = __importStar(require("../../../../core"));
const MessageId_1 = require("./MessageId");
const MessageThreadId_1 = require("./MessageThreadId");
const MessageSentAt_1 = require("./MessageSentAt");
const MessageFrom_1 = require("./MessageFrom");
const MessageSubject_1 = require("./MessageSubject");
const MessagePreview_1 = require("./MessagePreview");
const MessageTo_1 = require("./MessageTo");
const MessageCc_1 = require("./MessageCc");
const MessageBcc_1 = require("./MessageBcc");
const MessageText_1 = require("./MessageText");
const MessageHtml_1 = require("./MessageHtml");
const MessageAttachments_1 = require("./MessageAttachments");
exports.Message = core.serialization.object({
    messageId: core.serialization.property("message_id", MessageId_1.MessageId),
    threadId: core.serialization.property("thread_id", MessageThreadId_1.MessageThreadId),
    sentAt: core.serialization.property("sent_at", MessageSentAt_1.MessageSentAt),
    receivedAt: core.serialization.property("received_at", core.serialization.date()),
    from: MessageFrom_1.MessageFrom,
    replyTo: core.serialization.property("reply_to", core.serialization.string().optional()),
    subject: MessageSubject_1.MessageSubject,
    preview: MessagePreview_1.MessagePreview,
    to: MessageTo_1.MessageTo,
    cc: MessageCc_1.MessageCc,
    bcc: MessageBcc_1.MessageBcc,
    text: MessageText_1.MessageText,
    html: MessageHtml_1.MessageHtml,
    attachments: MessageAttachments_1.MessageAttachments,
    inReplyTo: core.serialization.property("in_reply_to", core.serialization.string().optional()),
    references: core.serialization.list(core.serialization.string()).optional(),
});
