/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageThreadId: core.serialization.Schema<serializers.MessageThreadId.Raw, AgentMailApi.MessageThreadId>;
export declare namespace MessageThreadId {
    type Raw = string;
}
