/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageText: core.serialization.Schema<serializers.MessageText.Raw, AgentMailApi.MessageText>;
export declare namespace MessageText {
    type Raw = string | null | undefined;
}
