/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageId } from "./MessageId";
import { MessageThreadId } from "./MessageThreadId";
import { MessageSentAt } from "./MessageSentAt";
import { MessageFrom } from "./MessageFrom";
import { MessageSubject } from "./MessageSubject";
import { MessagePreview } from "./MessagePreview";
import { MessageTo } from "./MessageTo";
import { MessageCc } from "./MessageCc";
import { MessageBcc } from "./MessageBcc";
import { MessageText } from "./MessageText";
import { MessageHtml } from "./MessageHtml";
import { MessageAttachments } from "./MessageAttachments";
export declare const Message: core.serialization.ObjectSchema<serializers.Message.Raw, AgentMailApi.Message>;
export declare namespace Message {
    interface Raw {
        message_id: MessageId.Raw;
        thread_id: MessageThreadId.Raw;
        sent_at: MessageSentAt.Raw;
        received_at: string;
        from: MessageFrom.Raw;
        reply_to?: string | null;
        subject?: MessageSubject.Raw;
        preview?: MessagePreview.Raw;
        to: MessageTo.Raw;
        cc?: MessageCc.Raw;
        bcc?: MessageBcc.Raw;
        text?: MessageText.Raw;
        html?: MessageHtml.Raw;
        attachments?: MessageAttachments.Raw;
        in_reply_to?: string | null;
        references?: string[] | null;
    }
}
