/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageId } from "./MessageId";
import { ThreadId } from "../../threads/types/ThreadId";
import { MessageSentAt } from "./MessageSentAt";
import { MessageFrom } from "./MessageFrom";
import { MessageSubject } from "./MessageSubject";
import { MessagePreview } from "./MessagePreview";
import { MessageTo } from "./MessageTo";
import { MessageCc } from "./MessageCc";
import { MessageBcc } from "./MessageBcc";
import { MessageAttachments } from "./MessageAttachments";
export declare const MessageItem: core.serialization.ObjectSchema<serializers.MessageItem.Raw, AgentMailApi.MessageItem>;
export declare namespace MessageItem {
    interface Raw {
        message_id: MessageId.Raw;
        thread_id: ThreadId.Raw;
        sent_at: MessageSentAt.Raw;
        from: MessageFrom.Raw;
        subject?: MessageSubject.Raw;
        preview?: MessagePreview.Raw;
        to: MessageTo.Raw;
        cc?: MessageCc.Raw;
        bcc?: MessageBcc.Raw;
        attachments?: MessageAttachments.Raw;
    }
}
