/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageFrom: core.serialization.Schema<serializers.MessageFrom.Raw, AgentMailApi.MessageFrom>;
export declare namespace MessageFrom {
    type Raw = string;
}
