/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageSentAt: core.serialization.Schema<serializers.MessageSentAt.Raw, AgentMailApi.MessageSentAt>;
export declare namespace MessageSentAt {
    type Raw = string;
}
