/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { Addresses } from "./Addresses";
export declare const SendMessageTo: core.serialization.Schema<serializers.SendMessageTo.Raw, AgentMailApi.SendMessageTo>;
export declare namespace SendMessageTo {
    type Raw = Addresses.Raw;
}
