/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { Addresses } from "./Addresses";
export declare const SendMessageCc: core.serialization.Schema<serializers.SendMessageCc.Raw, AgentMailApi.SendMessageCc>;
export declare namespace SendMessageCc {
    type Raw = Addresses.Raw | null | undefined;
}
