/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { SendMessageTo } from "./SendMessageTo";
import { SendMessageCc } from "./SendMessageCc";
import { SendMessageBcc } from "./SendMessageBcc";
import { MessageSubject } from "./MessageSubject";
import { MessageText } from "./MessageText";
import { MessageHtml } from "./MessageHtml";
export declare const SendMessageRequest: core.serialization.ObjectSchema<serializers.SendMessageRequest.Raw, AgentMailApi.SendMessageRequest>;
export declare namespace SendMessageRequest {
    interface Raw {
        to: SendMessageTo.Raw;
        cc?: SendMessageCc.Raw;
        bcc?: SendMessageBcc.Raw;
        subject?: MessageSubject.Raw;
        text?: MessageText.Raw;
        html?: MessageHtml.Raw;
    }
}
