/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { MessageThreadId } from "./MessageThreadId";
import { MessageId } from "./MessageId";
export declare const SendMessageResponse: core.serialization.ObjectSchema<serializers.SendMessageResponse.Raw, AgentMailApi.SendMessageResponse>;
export declare namespace SendMessageResponse {
    interface Raw {
        thread_id: MessageThreadId.Raw;
        message_id: MessageId.Raw;
    }
}
