/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as core from "../../../../core";
export declare const AttachmentNotFoundError: core.serialization.Schema<serializers.AttachmentNotFoundError.Raw, string>;
export declare namespace AttachmentNotFoundError {
    type Raw = string;
}
