/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as core from "../../../../core";
export declare const MessageNotFoundError: core.serialization.Schema<serializers.MessageNotFoundError.Raw, string>;
export declare namespace MessageNotFoundError {
    type Raw = string;
}
