/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { Attachment } from "../../attachments/types/Attachment";
export declare const MessageAttachments: core.serialization.Schema<serializers.MessageAttachments.Raw, AgentMail.MessageAttachments>;
export declare namespace MessageAttachments {
    type Raw = Attachment.Raw[];
}
