/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageCc: core.serialization.Schema<serializers.MessageCc.Raw, AgentMail.MessageCc>;
export declare namespace MessageCc {
    type Raw = string[];
}
