/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageSubject: core.serialization.Schema<serializers.MessageSubject.Raw, AgentMail.MessageSubject>;
export declare namespace MessageSubject {
    type Raw = string;
}
