/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessagePreview: core.serialization.Schema<serializers.MessagePreview.Raw, AgentMail.MessagePreview>;
export declare namespace MessagePreview {
    type Raw = string;
}
