/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const MessageHtml: core.serialization.Schema<serializers.MessageHtml.Raw, AgentMail.MessageHtml>;
export declare namespace MessageHtml {
    type Raw = string;
}
