"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SendMessageBcc = void 0;
const Addresses_1 = require("./Addresses");
exports.SendMessageBcc = Addresses_1.Addresses;
