/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Address of sender. In format `username@domain.com` or `Display Name <username@domain.com>`.
 */
export declare type MessageFrom = string;
