/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AgentMailApi from "../../../index";
/**
 * CC recipient address or addresses.
 */
export declare type SendMessageCc = AgentMailApi.Addresses | undefined;
