/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AgentMailApi from "../../../index";
/**
 * Recipient address or addresses.
 */
export declare type SendMessageTo = AgentMailApi.Addresses;
