/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AgentMailApi from "../../../index";
/**
 * BCC recipient address or addresses.
 */
export declare type SendMessageBcc = AgentMailApi.Addresses | undefined;
