/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const DraftTo: core.serialization.Schema<serializers.DraftTo.Raw, AgentMail.DraftTo>;
export declare namespace DraftTo {
    type Raw = string[];
}
