/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const DraftLabels: core.serialization.Schema<serializers.DraftLabels.Raw, AgentMail.DraftLabels>;
export declare namespace DraftLabels {
    type Raw = string[];
}
