/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const DraftUpdatedAt: core.serialization.Schema<serializers.DraftUpdatedAt.Raw, AgentMail.DraftUpdatedAt>;
export declare namespace DraftUpdatedAt {
    type Raw = string;
}
