/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const DraftCc: core.serialization.Schema<serializers.DraftCc.Raw, AgentMail.DraftCc>;
export declare namespace DraftCc {
    type Raw = string[];
}
