/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const DraftText: core.serialization.Schema<serializers.DraftText.Raw, AgentMail.DraftText>;
export declare namespace DraftText {
    type Raw = string;
}
