/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const ContextMetadata: core.serialization.Schema<serializers.ContextMetadata.Raw, AgentMail.ContextMetadata>;
export declare namespace ContextMetadata {
    type Raw = Record<string, unknown>;
}
