/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index";
import * as AgentMail from "../index";
export declare class ValidationError extends errors.AgentMailError {
    constructor(body: AgentMail.ValidationErrorResponse);
}
