/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../../../errors/index";
export declare class ThreadNotFoundError extends errors.AgentMailApiError {
    constructor(body: string);
}
