/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as AgentMailApi from "../../api/index";
import * as core from "../../core";
export declare const LastKey: core.serialization.Schema<serializers.LastKey.Raw, AgentMailApi.LastKey>;
export declare namespace LastKey {
    type Raw = string | null | undefined;
}
