/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as AgentMailApi from "../../api/index";
import * as core from "../../core";
export declare const Limit: core.serialization.Schema<serializers.Limit.Raw, AgentMailApi.Limit>;
export declare namespace Limit {
    type Raw = number;
}
