/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as AgentMailApi from "../../api/index";
import * as core from "../../core";
export declare const QueryLimit: core.serialization.Schema<serializers.QueryLimit.Raw, AgentMailApi.QueryLimit>;
export declare namespace QueryLimit {
    type Raw = number | null | undefined;
}
