/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as AgentMailApi from "../../api/index";
import * as core from "../../core";
import { ErrorName } from "./ErrorName";
export declare const ValidationErrorResponse: core.serialization.ObjectSchema<serializers.ValidationErrorResponse.Raw, AgentMailApi.ValidationErrorResponse>;
export declare namespace ValidationErrorResponse {
    interface Raw {
        name: ErrorName.Raw;
        errors?: unknown;
    }
}
