#!/usr/bin/env python3

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from urllib.request import Request, urlopen


MANIFEST_URL = "https://raw.githubusercontent.com/agentmail-to/agentmail-mcp/main/mcp-manifest.json"
OUTPUT = Path(__file__).resolve().parents[1] / "fern/snippets/mcp-tool-catalog.mdx"
TOOL_NAME = re.compile(r"^[a-z][a-z0-9_]*$")


def load_tools():
    request = Request(MANIFEST_URL, headers={"User-Agent": "agentmail-docs-tool-catalog"})
    with urlopen(request, timeout=30) as response:
        manifest = json.loads(response.read())

    if not isinstance(manifest, dict):
        raise ValueError("manifest must be an object")
    if manifest.get("server") != "to.agentmail/agentmail":
        raise ValueError("manifest has an unexpected server identity")
    if manifest.get("endpoint") != "https://mcp.agentmail.to/mcp":
        raise ValueError("manifest has an unexpected endpoint")

    tools = manifest.get("tools")
    if not isinstance(tools, list) or not tools:
        raise ValueError("manifest tools must be a non-empty list")

    names = set()
    for tool in tools:
        if not isinstance(tool, dict):
            raise ValueError("each manifest tool must be an object")
        name = tool.get("name")
        if not isinstance(name, str) or not TOOL_NAME.fullmatch(name):
            raise ValueError(f"invalid tool name: {name!r}")
        if name in names:
            raise ValueError(f"duplicate tool name: {name}")
        names.add(name)
        if not isinstance(tool.get("description"), str) or not tool["description"].strip():
            raise ValueError(f"tool {name} has no description")
        if not isinstance(tool.get("oauthOnly"), bool):
            raise ValueError(f"tool {name} has no oauthOnly flag")
    return tools


def table_cell(value):
    return " ".join(value.split()).replace("|", r"\|")


def render(tools):
    shared_count = sum(not tool["oauthOnly"] for tool in tools)
    oauth_count = len(tools) - shared_count
    lines = [
        "{/* Generated by scripts/generate_mcp_tool_catalog.py. Do not edit. */}",
        "",
        f"The runtime contract currently exposes **{shared_count} tools** to all authenticated sessions. OAuth sessions can also receive **{oauth_count} organization-selection tools**.",
        "",
        "| Tool | Description | Availability |",
        "| --- | --- | --- |",
    ]
    for tool in tools:
        availability = "OAuth only" if tool["oauthOnly"] else "All authenticated sessions"
        lines.append(
            f"| `{tool['name']}` | {table_cell(tool['description'])} | {availability} |"
        )
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate the MCP tool catalog from the canonical runtime manifest.")
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in catalog is out of date.")
    args = parser.parse_args()

    try:
        generated = render(load_tools())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Unable to generate MCP tool catalog: {error}", file=sys.stderr)
        return 2

    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if args.check:
        if current == generated:
            print("MCP tool catalog is current.")
            return 0
        print("MCP tool catalog is out of date. Run scripts/generate_mcp_tool_catalog.py.", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile=str(OUTPUT),
                tofile=f"{OUTPUT} (generated)",
            )
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"Generated {OUTPUT}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
