#!/usr/bin/env python3

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from urllib.request import Request, urlopen


MANIFEST_URL = "https://raw.githubusercontent.com/agentmail-to/agentmail-mcp/main/mcp-manifest.json"
MANIFEST = Path(__file__).resolve().parent / "mcp-manifest.json"
OUTPUT = Path(__file__).resolve().parents[1] / "fern/snippets/mcp-tool-catalog.mdx"
TOOL_NAME = re.compile(r"^[a-z][a-z0-9_]*$")


def fetch_manifest():
    request = Request(MANIFEST_URL, headers={"User-Agent": "agentmail-docs-tool-catalog"})
    with urlopen(request, timeout=30) as response:
        MANIFEST.write_bytes(response.read())
    print(f"Fetched {MANIFEST_URL} -> {MANIFEST}.")


def load_manifest():
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))

    if not isinstance(manifest, dict):
        raise ValueError("manifest must be an object")
    if manifest.get("server") != "to.agentmail/agentmail":
        raise ValueError("manifest has an unexpected server identity")
    if manifest.get("endpoint") != "https://mcp.agentmail.to/mcp":
        raise ValueError("manifest has an unexpected endpoint")

    tools = manifest.get("tools")
    if not isinstance(tools, list) or not tools:
        raise ValueError("manifest tools must be a non-empty list")

    names = set()
    for tool in tools:
        if not isinstance(tool, dict):
            raise ValueError("each manifest tool must be an object")
        name = tool.get("name")
        if not isinstance(name, str) or not TOOL_NAME.fullmatch(name):
            raise ValueError(f"invalid tool name: {name!r}")
        if name in names:
            raise ValueError(f"duplicate tool name: {name}")
        names.add(name)
        if not isinstance(tool.get("description"), str) or not tool["description"].strip():
            raise ValueError(f"tool {name} has no description")
        if not isinstance(tool.get("oauthOnly"), bool):
            raise ValueError(f"tool {name} has no oauthOnly flag")
    return manifest


GROUPS = [
    ("Inboxes", "inbox"),
    ("Threads", "thread"),
    ("Messages", "message"),
    ("Drafts", "draft"),
    ("Attachments", "attachment"),
    ("Auth", "auth"),
    ("Organizations (OAuth sessions only)", "organization"),
]


def group_for(name):
    for title, keyword in GROUPS:
        if keyword in name:
            return title
    raise ValueError(f"tool {name} matches no resource group; update GROUPS")


def table_cell(value):
    return " ".join(value.split()).replace("|", r"\|")


def render(manifest):
    tools = manifest["tools"]
    shared_count = sum(not tool["oauthOnly"] for tool in tools)
    oauth_count = len(tools) - shared_count
    grouped = {}
    for tool in tools:
        grouped.setdefault(group_for(tool["name"]), []).append(tool)
    lines = [
        f"{{/* Generated by scripts/generate_mcp_tool_catalog.py from manifest {manifest.get('digest', 'unknown')}. Do not edit. */}}",
        "",
        f"The server exposes **{shared_count} tools**, grouped by resource. OAuth sessions also receive **{oauth_count} organization-selection tools**.",
    ]
    for title, _ in GROUPS:
        if title not in grouped:
            continue
        lines += ["", f"### {title}", "", "| Tool | Description |", "| --- | --- |"]
        for tool in grouped[title]:
            lines.append(f"| `{tool['name']}` | {table_cell(tool['description'])} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate the MCP tool catalog from the vendored runtime manifest.")
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in catalog does not match the vendored manifest.")
    parser.add_argument("--fetch", action="store_true", help="Refresh the vendored manifest from the canonical repository first.")
    args = parser.parse_args()

    try:
        if args.fetch:
            fetch_manifest()
        generated = render(load_manifest())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Unable to generate MCP tool catalog: {error}", file=sys.stderr)
        return 2

    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if args.check:
        if current == generated:
            print("MCP tool catalog is current.")
            return 0
        print("MCP tool catalog is out of date. Run scripts/generate_mcp_tool_catalog.py.", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile=str(OUTPUT),
                tofile=f"{OUTPUT} (generated)",
            )
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"Generated {OUTPUT}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
