/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { ThreadItem } from "./ThreadItem";
import { Limit } from "../../../types/Limit";
import { Count } from "../../../types/Count";
import { LastKey } from "../../../types/LastKey";
export declare const ListThreadsResponse: core.serialization.ObjectSchema<serializers.ListThreadsResponse.Raw, AgentMailApi.ListThreadsResponse>;
export declare namespace ListThreadsResponse {
    interface Raw {
        threads: ThreadItem.Raw[];
        limit: Limit.Raw;
        count: Count.Raw;
        last_key?: LastKey.Raw;
    }
}
