/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const ThreadSubject: core.serialization.Schema<serializers.ThreadSubject.Raw, AgentMailApi.ThreadSubject>;
export declare namespace ThreadSubject {
    type Raw = string | null | undefined;
}
