/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const ThreadUpdatedAt: core.serialization.Schema<serializers.ThreadUpdatedAt.Raw, AgentMailApi.ThreadUpdatedAt>;
export declare namespace ThreadUpdatedAt {
    type Raw = string;
}
