/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { ThreadId } from "./ThreadId";
import { InboxId } from "../../inboxes/types/InboxId";
import { ThreadUpdatedAt } from "./ThreadUpdatedAt";
import { ThreadSubject } from "./ThreadSubject";
import { ThreadParticipants } from "./ThreadParticipants";
import { Message } from "../../messages/types/Message";
export declare const Thread: core.serialization.ObjectSchema<serializers.Thread.Raw, AgentMailApi.Thread>;
export declare namespace Thread {
    interface Raw {
        thread_id: ThreadId.Raw;
        inbox_id: InboxId.Raw;
        created_at: string;
        updated_at: ThreadUpdatedAt.Raw;
        subject?: ThreadSubject.Raw;
        participants: ThreadParticipants.Raw;
        messages: Message.Raw[];
    }
}
