/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const ThreadParticipants: core.serialization.Schema<serializers.ThreadParticipants.Raw, AgentMailApi.ThreadParticipants>;
export declare namespace ThreadParticipants {
    type Raw = string[];
}
