"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Thread = void 0;
const core = __importStar(require("../../../../core"));
const ThreadId_1 = require("./ThreadId");
const InboxId_1 = require("../../inboxes/types/InboxId");
const ThreadUpdatedAt_1 = require("./ThreadUpdatedAt");
const ThreadSubject_1 = require("./ThreadSubject");
const ThreadParticipants_1 = require("./ThreadParticipants");
const Message_1 = require("../../messages/types/Message");
exports.Thread = core.serialization.object({
    threadId: core.serialization.property("thread_id", ThreadId_1.ThreadId),
    inboxId: core.serialization.property("inbox_id", InboxId_1.InboxId),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", ThreadUpdatedAt_1.ThreadUpdatedAt),
    subject: ThreadSubject_1.ThreadSubject,
    participants: ThreadParticipants_1.ThreadParticipants,
    messages: core.serialization.list(Message_1.Message),
});
