/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMailApi from "../../../../api/index";
import * as core from "../../../../core";
import { ThreadId } from "./ThreadId";
import { ThreadUpdatedAt } from "./ThreadUpdatedAt";
import { ThreadParticipants } from "./ThreadParticipants";
import { ThreadSubject } from "./ThreadSubject";
import { ThreadPreview } from "./ThreadPreview";
export declare const ThreadItem: core.serialization.ObjectSchema<serializers.ThreadItem.Raw, AgentMailApi.ThreadItem>;
export declare namespace ThreadItem {
    interface Raw {
        thread_id: ThreadId.Raw;
        updated_at: ThreadUpdatedAt.Raw;
        participants: ThreadParticipants.Raw;
        subject?: ThreadSubject.Raw;
        preview?: ThreadPreview.Raw;
    }
}
