/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { Count } from "../../../types/Count";
import { Limit } from "../../../types/Limit";
import { PageToken } from "../../../types/PageToken";
import { Webhook } from "./Webhook";
export declare const ListWebhooksResponse: core.serialization.ObjectSchema<serializers.ListWebhooksResponse.Raw, AgentMail.ListWebhooksResponse>;
export declare namespace ListWebhooksResponse {
    interface Raw {
        count: Count.Raw;
        limit?: Limit.Raw | null;
        next_page_token?: PageToken.Raw | null;
        webhooks: Webhook.Raw[];
    }
}
