/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const SvixTimestamp: core.serialization.Schema<serializers.SvixTimestamp.Raw, AgentMail.SvixTimestamp>;
export declare namespace SvixTimestamp {
    type Raw = string;
}
