/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const AttachmentSize: core.serialization.Schema<serializers.AttachmentSize.Raw, AgentMail.AttachmentSize>;
export declare namespace AttachmentSize {
    type Raw = number;
}
