/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const AttachmentContent: core.serialization.Schema<serializers.AttachmentContent.Raw, AgentMail.AttachmentContent>;
export declare namespace AttachmentContent {
    type Raw = string;
}
