/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { AttachmentFilename } from "./AttachmentFilename";
import { AttachmentContentType } from "./AttachmentContentType";
import { AttachmentContent } from "./AttachmentContent";
export declare const SendAttachment: core.serialization.ObjectSchema<serializers.SendAttachment.Raw, AgentMail.SendAttachment>;
export declare namespace SendAttachment {
    interface Raw {
        filename?: AttachmentFilename.Raw | null;
        content_type?: AttachmentContentType.Raw | null;
        content: AttachmentContent.Raw;
    }
}
