/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { ContextId } from "./ContextId";
import { ContextType } from "./ContextType";
import { ContextData } from "./ContextData";
import { ContextMetadata } from "./ContextMetadata";
import { ContextIsEvent } from "./ContextIsEvent";
export declare const Context: core.serialization.ObjectSchema<serializers.Context.Raw, AgentMail.Context>;
export declare namespace Context {
    interface Raw {
        context_id: ContextId.Raw;
        type: ContextType.Raw;
        data: ContextData.Raw;
        metadata?: ContextMetadata.Raw | null;
        is_event: ContextIsEvent.Raw;
        updated_at: string;
        created_at: string;
    }
}
