/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { InboxId } from "../../inboxes/types/InboxId";
import { ThreadId } from "../../threads/types/ThreadId";
import { DraftId } from "./DraftId";
import { DraftLabels } from "./DraftLabels";
import { DraftReplyTo } from "./DraftReplyTo";
import { DraftTo } from "./DraftTo";
import { DraftCc } from "./DraftCc";
import { DraftBcc } from "./DraftBcc";
import { DraftSubject } from "./DraftSubject";
import { DraftPreview } from "./DraftPreview";
import { DraftText } from "./DraftText";
import { DraftHtml } from "./DraftHtml";
import { DraftAttachments } from "./DraftAttachments";
import { DraftUpdatedAt } from "./DraftUpdatedAt";
export declare const Draft: core.serialization.ObjectSchema<serializers.Draft.Raw, AgentMail.Draft>;
export declare namespace Draft {
    interface Raw {
        inbox_id: InboxId.Raw;
        thread_id: ThreadId.Raw;
        draft_id: DraftId.Raw;
        labels: DraftLabels.Raw;
        reply_to?: DraftReplyTo.Raw | null;
        to?: DraftTo.Raw | null;
        cc?: DraftCc.Raw | null;
        bcc?: DraftBcc.Raw | null;
        subject?: DraftSubject.Raw | null;
        preview?: DraftPreview.Raw | null;
        text?: DraftText.Raw | null;
        html?: DraftHtml.Raw | null;
        attachments?: DraftAttachments.Raw | null;
        in_reply_to?: string | null;
        references?: string[] | null;
        updated_at: DraftUpdatedAt.Raw;
        created_at: string;
    }
}
