/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
export declare const DraftPreview: core.serialization.Schema<serializers.DraftPreview.Raw, AgentMail.DraftPreview>;
export declare namespace DraftPreview {
    type Raw = string;
}
